name: ci
on:
  push:
    branches: [main]

jobs:
  build-linux:
    name: Build Linux Binary
    runs-on: ubuntu-latest
    needs: [check-deps]

    container:
      image: golang:1.23

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Install SDL2
        run: apt install libsdl2{,-image,-mixer,-ttf,-gfx}-dev

      - name: Install dependencies
        run: go mod download

      - name: Build
        env:
          OS: linux
          ARCH: amd64
          O_DIR: bin
          ENV: ${{ env.ENVIRONMENT }}
        run: make build

      - name: Upload artifacts
        uses: actions/updateload-artifact@v3
        with:
          name: main
          path: ./bin/

